blank_issues_enabled: false
contact_links:
  - name: Public Documentation (unrealsharp.com)
    url: https://github.com/UnrealSharp/unrealsharp.github.io
    about: For all unrealsharp.com related requests and issues